### ISSUE TITLE
Problem with xcb plugin

### ISSUE THREAD

**Issue by aglpy** [rgerum/pylustrator#11]
I am using bash consolo on windows and with a virtualenv, I can import pylustrator but when I execute 'pylustrator.start()' the following error is showing:

```python
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

If I replicate all in the Windows cmd it run correctly.

**Comment by tacaswell** [comment]
This is an issues with your Qt installation, see https://github.com/matplotlib/matplotlib/issues/7597/ for related discussion.

**Comment by rgerum** [comment]
As it seems to be an issue directly with Qt and the matplotlib installation, it is probably not directly related to pylustrator.
