### ISSUE TITLE
Add to matplotlib contributed ?

### ISSUE THREAD

**Issue by benoitrosa** [rgerum/pylustrator#30]
This is not really an issue, but matplotlib maintains a list of user-contributed packages, which is highlighted here : https://matplotlib.org/mpl-third-party/

To be highlighted there, a PR should be done here : https://github.com/matplotlib/mpl-third-party

I think pylustrator is amazing and would gladly do that, but asking the permission here because normally authors should be doing this, not users ;)

**Comment by rgerum** [comment]
Thanks for the suggestion. I created a pull request, let's see if they add it.

**Comment by rgerum** [comment]
They accepted the pull request.
