### ISSUE TITLE
Exception when trying to edit text/labels

### ISSUE THREAD

**Issue by cycomanic** [rgerum/pylustrator#32]
Great project! Really what was missing for matplotlib

I'm trying to adjust some figures and I get an exception when trying to edit any text object (including axis labels). 
As a test-case I generate a plot using the script below:
```python
import matplotlib.pyplot as plt
import pylustrator
import numpy as np
pylustrator.start()

plt.plot(np.arange(10), np.arange(10))
plt.show()
```
If I then edit the xlabel I get the following exception:
```
Traceback (most recent call last):
  File "/home/jschrod/.local/lib/python3.9/site-packages/pylustrator/QLinkableWidgets.py", line 120, in updateLink
    elements = self.setLinkedProperty(self.get())
  File "/home/jschrod/.local/lib/python3.9/site-packages/pylustrator/QLinkableWidgets.py", line 67, in set
    if isinstance(self.element, Text) and isinstance(self.element.figure.selection.targets[0].target, Axes):
IndexError: list index out of range
```

**Comment by rgerum** [comment]
hmm strange. What do you exactly do? Probably "click on the plot" and then "enter text in the xlabel box" and then when you click away from it the error occurs?
