### ISSUE TITLE
svg file editting

### ISSUE THREAD

**Issue by xihajun** [rgerum/pylustrator#34]
Hi, thanks for this nice tools.

I wonder if that works for import svg file generated by python as well. maybe things like plt.imshow?

**Comment by rgerum** [comment]
Hi, I am sorry but I don't quite understand what your request is about. Could you elaborate a bit more?
You want to import svg which was generated on the fly by python without loading it from file?
If yes, how do you generate it? But I guess the representation of the svg then depends on the package that creates it. So maybe the easiest way would be to write it to an io stream and pass that into the function

**Comment by xihajun** [comment]
Thanks a lot! you are right, I think the `pylustrator.load` works magically.
