### ISSUE TITLE
[Buggy] menu disappears when opening up large figure with size 15*15 

### ISSUE THREAD

**Issue by xihajun** [rgerum/pylustrator#35]
If I open a figure with size 15*15, the menu would be disappear (but just a tinny buggy for large image I guess)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25631641/145654237-a4bbb3c8-f906-47e2-8028-2adbc72811da.png">
Here is a view for a full screen

**Comment by rgerum** [comment]
I implemented an automatic zoom out for large images to fit the screen. This should fix your issue. bd4db15b32cb30a61b05752112de303c73fb3c02
