### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Atcold** [rgerum/pylustrator#36]
When I try running the following code I get two white screens.

```python
from matplotlib.pylab import *
π = pi

import pylustrator
pylustrator.start()

t = linspace(0, 1)
x = sin(2 * π * t)
plot(t, x)
show()
```

![image](https://user-images.githubusercontent.com/2119355/155648074-429679a7-580b-4a9f-a1d2-8e4ebb1555a9.png)

```
$ python sine.py 
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/book/lib/python3.10/site-packages/pylustrator/QtGuiDrag.py", line 1122, in closeEvent
    if not self.fig.change_tracker.saved:
AttributeError: 'Figure' object has no attribute 'change_tracker'
```

Commenting out the pylustrator's line, I get the following.

![image](https://user-images.githubusercontent.com/2119355/155648319-96381c0a-c595-4c31-b8a1-3d3b815ca5ae.png)

I'm using `matplotlib 3.5.1`.

**Comment by rgerum** [comment]
Apparently pylustrator does not work when using the pylab * import.
I would strongly recommend to import matplotlib and numpy directly with "import matplotlib.pyplot as plt" and "import numpy as np" as it makes the code more readable. For example if you use "max" it is not clear if you are using the builtin function max or the numpy function max, as your approach silently overwrote it.

As pylustrator overloads the plt.figure and plt.show commands, it cannot work if you have already imported them directly without still being in the namespace of a module.
Therefore, you need to write it like this when using pylustrator.

```python
import matplotlib.pyplot as plt
import numpy as np
π = np.pi

import pylustrator
pylustrator.start()

t = np.linspace(0, 1)
x = np.sin(2 * π * t)
plt.plot(t, x)
plt.show()
```

**Comment by rgerum** [comment]
if you want to keep your code like this, you can alternatively just use plt.show() for opening the pylustrator and leave the rest as it is. As just this is the crucial part.

So this also works, although I would recommend against importing with *
from matplotlib.pylab import *
π = pi

```python
import pylustrator
pylustrator.start()

t = linspace(0, 1)
x = sin(2 * π * t)
plot(t, x)
import matplotlib.pyplot as plt
plt.show()
```

**Comment by Atcold** [comment]
Oh, thanks! It does work! 🎉

Thanks for the recommendation as well, but I'd rather use a calculator without the need to tell it where to find its functions. If I do write code, then yes, I use namespaces. If I do maths, then no, it just bogs down the thinking.

Finally, not sure this is a bug, but the button strings are quite illegible.
![image](https://user-images.githubusercontent.com/2119355/155829949-3b7f5e37-8883-4bcc-8699-beff1e40345c.png)

Also, I believe some `y`'s are missing.
![image](https://user-images.githubusercontent.com/2119355/155830069-07c91508-edc5-443f-8896-26df06ca2a8c.png)
