### ISSUE TITLE
iPython support please

### ISSUE THREAD

**Issue by kvngvikram** [rgerum/pylustrator#37]
Thanks for making pylustrator.
Just that I mostly work in ipython prompt. So It will be really awesome if I can use this within ipython.

Maybe just do my usual stuff in ipython and then when I want to edit things call some magic function which will edit the currently active figure. And once customizing is done, just print the automatically generated code onto the screen instead of trying to edit any file (also just run them for me :) ).

I am not good enough to add this feature myself. At least give me a direction?

**Comment by rgerum** [comment]
Well I disabled it on purpose as it might confuse the user. But now I implemented it and print some warnings so that users do not get confused that the changes are not saved but just printed to the console output.
