### ISSUE TITLE
Feature request: loading and editing pickle-dumped figures

### ISSUE THREAD

**Issue by arashgmn** [rgerum/pylustrator#39]
First of all, awesome work! Thank you. 

Matplotlib folks suggest saving figure objects as a pickle for later modification. 

```python3
import matplotlib.pyplot as plt
import pickle 

# plot a fancy figure
# ...

fig = plt.gcf()
pickle.dump(fig, open('figObj.pickle', 'wb')) # for future
```
I was thinking it would be truly amazing if pylustrator could pick up the editing job from those saved picked. Something like this:

```python3
import matplotlib.pyplot as plt
import pylustrator
pylustrator.start()

pylustrator.pickle_load('figObj.pickle') # interactive editing 
```

Looking forward to the future of pylustrator!
Arash

**Comment by rgerum** [comment]
I am not sure if i want to recommend people using pickel files as they are not intended for long term storage as the serialisation can change between python versions.
But I can have a look if it is possible to implemented such a feature for pylustrator.

**Comment by rgerum** [comment]
With this commit you should be able to start pylustrator after figure generation. Which means you should be able to load your figure from pickle first and then start pylustrator. You can install the repository version with

    pip install git+https://github.com/rgerum/pylustrator
