### ISSUE TITLE
Make the panels resizeable

### ISSUE THREAD

**Issue by fconil** [rgerum/pylustrator#42]
Hi,

I just tried Pylustrator with the example code and I like your idea.

I am using Ubuntu 22.04, Python 3.10, Pylustrator runs in a virtual environment.

If the screen resolution is too high (3840 x 2160, scale 200%), the right panel is not usable : the controls are too small.

It would be nice, if you can make the panels  resizeable.

Regards

<img src="https://user-images.githubusercontent.com/809748/185186014-5be696b8-5153-42e5-96ba-cd847c80155f.png" height="400"/>

**Comment by rgerum** [comment]
I made the toolbar resizable. But now the left bar also extends when resizing the window. I am not sure how to convince Qt otherwise...

**Comment by AlainOUYANG** [comment]
A similar problem on macOS 12.5.1 (with the portion in the red rectangle):

![resize](https://user-images.githubusercontent.com/22619010/192493990-9a03e918-adb0-4f1a-82c3-54089452cec4.png)

**Comment by fconil** [comment]
Having some control under the menu bar is a good improvement.

I can not capture the mouse cursor but when it is in the "green" area, but its shape changes to a form that make me believe I can resize the panels. Unfortunately, it has not effect.

As a consequence, some controls are still difficult to use (x-Label, x-Lim) without panel resize. The size seems fixed to the size it gets at launch.

![pylustrator-panel-not-resizable](https://user-images.githubusercontent.com/809748/192769276-69dfffba-bee1-4220-a656-1966db87cdfd.png)

**Comment by rgerum** [comment]
The panel is now properly resizeable. Took me a while to figure out how to best implement that with the Qt sizing policies.
