### ISSUE TITLE
`ImportError: cannot import name 'SubFigure' from 'matplotlib.figure`'

### ISSUE THREAD

**Issue by trettelbach** [rgerum/pylustrator#50]
When importing pylustrator (to run the _example_pylustrator.py_ script), I get the message 
`ImportError: cannot import name 'SubFigure' from 'matplotlib.figure`'
and looking into the matplotlib.figure documentation, I cannot find any class named 'SubFigure', only 'Figure' or 'SubplotParams'. pylustrator is installed though.

Would appreciate any info on this. The tool looks so cool and I'd love to make it work on my machine :)

**Comment by rgerum** [comment]
Oh it seems that you use an older Matplotlib version where they did not yet have SubFigures. I should make the import of SubFigure optional so pylustrator works also with older Matplotlib versions.

**Comment by trettelbach** [comment]
Awesome thanks for the quick fix! Works now and I am very amazed.
