### ISSUE TITLE
removal of auto save popup window

### ISSUE THREAD

**Issue by darkcurrent** [rgerum/pylustrator#51]
Hello,

I want to add pylustrator into an application for non programmers. When pylustrator closed without saving, this popup is shown below. This is very useful for a lot of purposes but in this way the users of my application can accidently and easily update main application files which is not wanted. How can I remove this auto save popup? Thank you...

![image](https://user-images.githubusercontent.com/6089944/198838508-0ed3261a-b9cc-481e-a12c-a84a613ed0c2.png)

**Comment by rgerum** [comment]
hmm I could add a parameter to pylustrator.start to not ask for saving. But the user could still save the figure to the code. What is the use case? Shall the users only  be able to save it to an image and not to the code? Or do you just want to get rid of the promt?

**Comment by darkcurrent** [comment]
Thank you for your fast answer rgerum.
We will developing a software to collect data from Twitter, filter the data, auto-train and select NLP models, analyse the data and generate some report file with some graphics. This open source app will be made for completely non programmer social scientist.  In the end, we want the users only can generate images and save it but the default plot parameters should be static. So the main app files can not be changed. :)   Is there any way to implement this easily?

**Comment by rgerum** [comment]
ah ok, so you want to disable all saving to code and not just the prompt (you can also save using CTRL+S).
But yes it sounds feasible to implement this as a parameter to pylustrator.start, e.g. as pylustrator.start(save_code=False).

**Comment by darkcurrent** [comment]
> ah ok, so you want to disable all saving to code and not just the prompt (you can also save using CTRL+S). But yes it sounds feasible to implement this as a parameter to pylustrator.start, e.g. as pylustrator.start(save_code=False).

Yes exactly.  `pylustrator.start(save_code=False)` this looks life saver :)

**Comment by rgerum** [comment]
it is now implemented as `pylustrator.start(disable_save=True)`
